button_card_templates:
  !include_dir_merge_named button_card_templates

views:
  - title: Smart Gateways - Smart Meter Gateway
    path: smart-gateways-p1-gateway
    icon: mdi:lightning-bolt-circle
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: gauge
            entity: sensor.currently_energy_delivered_watt
            max: 5000
            min: 0
            needle: true
            severity:
              green: 0
              yellow: 800
              red: 1500
            name: Current usage
          - type: gauge
            entity: sensor.currently_energy_returned_watt
            max: 5000
            min: 0
            needle: true
            severity:
              green: 0
              yellow: 800
              red: 1500
            name: Current return
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: sensor.dsmr_reading_electricity_delivered_1
                icon: mdi:lightning-bolt
                secondary_info: none
              - entity: sensor.dsmr_reading_electricity_delivered_2
              - entity: sensor.dsmr_reading_electricity_returned_1
              - entity: sensor.dsmr_reading_electricity_returned_2
              - entity: sensor.dsmr_consumption_gas_delivered
                secondary_info: none
                icon: mdi:fire
              - entity: sensor.smartmeter_waterdelivered
                icon: mdi:water
                name: Water usage
      - type: custom:apexcharts-card
        experimental:
          color_threshold: true
        graph_span: 1h
        show:
          last_updated: true
        header:
          standard_format: false
          show: true
          show_states: true
          colorize_states: true
          title: Usage per phase last hour
        series:
          - entity: sensor.currently_power_usage_l1_watt
            type: line
            group_by:
              func: last
              duration: 10s
            stroke_width: 2
#            unit: Watt
          - entity: sensor.currently_power_usage_l2_watt
            type: line
            group_by:
              func: last
              duration: 10s
            stroke_width: 2
#            unit: Watt
          - entity: sensor.currently_power_usage_l3_watt
            type: line
            group_by:
              func: last
              duration: 10s
            stroke_width: 2
#            unit: Watt
      - type: custom:apexcharts-card
        experimental:
          color_threshold: true
        graph_span: 1h
        show:
          last_updated: true
        header:
          standard_format: false
          show: true
          show_states: true
          colorize_states: true
          title: Return per phase last hour
        series:
          - entity: sensor.currently_power_return_l1_watt
            type: line
            group_by:
              func: last
              duration: 10s
            stroke_width: 2
#            unit: Watt
          - entity: sensor.currently_power_return_l2_watt
            type: line
            group_by:
              func: last
              duration: 10s
            stroke_width: 2
#            unit: Watt
          - entity: sensor.currently_power_return_l3_watt
            type: line
            group_by:
              func: last
              duration: 10s
            stroke_width: 2
#            unit: Watt
      - type: custom:apexcharts-card
        graph_span: 24h
        span:
          start: day
        header:
          show: true
          title: Usage last 24 hours
        apex_config:
          yaxis:
            - id: first
              forceNiceScale: true
              decimalsInFloat: 2
              opposite: false
              name: Energie
        series:
          - entity: sensor.energy_usage_peak_hourly
            unit: kWh
            type: column
            name: High tariff usage
            color: '#EF810E'
            group_by:
              func: max
            show:
              datalabels: false
              extremas: false
          - entity: sensor.energy_usage_offpeak_hourly
            unit: kWh
            type: column
            name: Low tariff usage
            color: '#053752'
            group_by:
              func: max
            show:
              datalabels: false
              extremas: false
      - type: custom:apexcharts-card
        graph_span: 24h
        span:
          start: day
        header:
          show: true
          title: Returned last 24 hours
        apex_config:
          yaxis:
            - id: first
              forceNiceScale: true
              decimalsInFloat: 0
              opposite: false
              name: Water
        series:
          - entity: sensor.energy_return_peak_hourly
            unit: kWh
            type: column
            name: Low tariff returned
            color: '#EF810E'
            group_by:
              func: max
            show:
              datalabels: false
              extremas: false
          - entity: sensor.energy_return_offpeak_hourly
            unit: kWh
            type: column
            name: High tariff returned
            color: '#053752'
            group_by:
              func: max
            show:
              datalabels: false
              extremas: false
      - type: custom:apexcharts-card
        experimental:
          color_threshold: true
        graph_span: 24h
        show:
          last_updated: true
        header:
          standard_format: false
          show: true
          show_states: true
          colorize_states: true
          title: Voltage per phase last 24 hours
        span:
          start: day
        series:
          - entity: sensor.dsmr_reading_phase_voltage_l1
            type: line
            group_by:
              func: last
              duration: 15m
            stroke_width: 5
          - entity: sensor.dsmr_reading_phase_voltage_l2
            type: line
            group_by:
              func: last
              duration: 15m
            stroke_width: 5
          - entity: sensor.dsmr_reading_phase_voltage_l3
            type: line
            group_by:
              func: last
              duration: 15m
            stroke_width: 5
      - type: custom:apexcharts-card
        experimental:
          color_threshold: true
        graph_span: 1h
        show:
          last_updated: true
        apex_config:
          yaxis:
            - id: first
              forceNiceScale: true
              decimalsInFloat: 3
        header:
          standard_format: false
          show: true
          show_states: true
          colorize_states: true
          title: Current power usage and return
        series:
          - entity: sensor.currently_energy_delivered_watt
            name: Usage
            type: line
            group_by:
              func: last
              duration: 1m
            stroke_width: 5
            show:
              header_color_threshold: true
            color_threshold:
              - value: 0
                color: '#F8CFC9'
              - value: 0.5
                color: '#EE8E81'
              - value: 0.8
                color: '#E44D3A'
              - value: 1.5
                color: '#BC2C1A'
              - value: 3
                color: '#7E1E11'
          - entity: sensor.currently_energy_returned_watt
            name: Return
            type: line
            group_by:
              func: last
              duration: 1m
            stroke_width: 5
            show:
              header_color_threshold: true
            color_threshold:
              - value: 0
                color: '#D4ECE7'
              - value: 0.5
                color: '#9CD3C6'
              - value: 0.8
                color: '#71C1AE'
              - value: 1.5
                color: '#38806F'
              - value: 3
                color: '#19391'
      - type: custom:apexcharts-card
        experimental:
          color_threshold: true
        graph_span: 24h
        show:
          last_updated: true
        header:
          standard_format: false
          show: true
          show_states: true
          colorize_states: true
          title: Current per phase last 24 hours
        span:
          start: day
        series:
          - entity: sensor.dsmr_reading_phase_power_current_l1
            type: line
            group_by:
              func: last
              duration: 1m
            stroke_width: 2
          - entity: sensor.dsmr_reading_phase_power_current_l2
            type: line
            group_by:
              func: last
              duration: 1m
            stroke_width: 2
          - entity: sensor.dsmr_reading_phase_power_current_l3
            type: line
            group_by:
              func: last
              duration: 1m
            stroke_width: 2
      - type: custom:apexcharts-card
        graph_span: 24h
        span:
          start: day
        header:
          show: true
          title: Gas usage last 24 hours
        apex_config:
          yaxis:
            - id: first
              forceNiceScale: true
              decimalsInFloat: 3
              opposite: false
              name: Gas
        series:
          - entity: sensor.gas_usage_hourly
            unit: m3
            type: column
            name: gasverbruik
            color: '#EF810E'
            group_by:
              func: max
            show:
              datalabels: false
              extremas: false
      - type: entities
        entities:
          - entity: sensor.smartmeter_mac_address
          - entity: sensor.smartmeter_ip_address
          - entity: sensor.smartmeter_startup_time
          - entity: sensor.smartmeter_wifi_signal_strength_rssi
          - entity: sensor.smartmeter_firmware_running_version
          - entity: sensor.smartmeter_firmware_available_version
          - entity: sensor.smartmeter_firmware_update_available
          - entity: switch.smartmeter_install_firmware_update
          - entity: sensor.smartmeter_lastchanged
          - entity: binary_sensor.smartmeter_connectivity_status
        show_header_toggle: false
        title: SmartGateways.nl - Smart Meter Gateway
        state_color: true
      - type: gauge
        entity: sensor.smartmeter_wifi_signal_strength_rssi
        name: Gateway Signal Strength
        unit: dB
        min: -85
        max: -20
        needle: true
        severity:
          green: -67
          yellow: -76
          red: -90