- alias: Hallway Light Motion - We don't like this one
  id: hallway_light_motion
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.hallway_motion_sensor_occupancy
      light_target:
        entity_id: light.hallway_light
      no_motion_wait: 30
