- alias: Hallway Light Motion Extended (Blueprint)
  id: hallway_light_motion_extended
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
        - binary_sensor.hallway_motion_sensor_occupancy
      light_switch:
        entity_id: light.hallway_light
      time_delay: 0.5
      include_ambient: ambient_enabled
      ambient_light_sensor: sensor.hallway_motion_sensor_illuminance
      ambient_light_options: ambient_light_option_enabled

- alias: "Frigate Notifications"
  id: frigate_notifications
  use_blueprint:
    path: SgtBatten/Beta.yaml
    input:
      camera:
        - camera.driveway
        - camera.backyard
      notify_device: e4405accf87ba6b900191d60c1299b05
      base_url: https://ha.mczlik.com
      critical: "true"
      video: >-
        {{base_url}}/api/frigate{{client_id}}/notifications/{{review_id}}/review_preview.gif?format=ts
      final_update: true
      attachment_2: >-
        {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1
      icon: >-
        mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
        else 'cat' if label == 'Cat' else 'car' if label == 'Car' else
        'home-assistant'}}
      android_auto: true
      sticky: true
      loiter_timer: 60
      telegram_base_url: http://homeassistant.internal
      notify_telegram_chat_id: "<telegram_chat_id>"

- alias: Office speakers follow PC power
  id: office_speakers_follow_pc_power
  mode: single
  trigger:
    - id: pc_high
      platform: numeric_state
      entity_id: sensor.office_pc_switch_power
      above: 100
      for: "00:01:00"
    - id: pc_low
      platform: numeric_state
      entity_id: sensor.office_pc_switch_power
      below: 30
      for: "00:00:30"
  condition: []
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: pc_high
          sequence:
            - service: switch.turn_on
              target:
                entity_id: switch.office_speaker_switch
        - conditions:
            - condition: trigger
              id: pc_low
          sequence:
            - service: switch.turn_off
              target:
                entity_id: switch.office_speaker_switch

- alias: Poll LEDVANCE Energy every 5 min
  id: poll_ledvance_switches
  mode: single
  trigger:
    - platform: time_pattern
      minutes: "/5"
  action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/Office PC Switch/get
        payload: '{"energy": ""}'
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/Office Desk Switch/get
        payload: '{"energy": ""}'
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/Office Speaker Switch/get
        payload: '{"energy": ""}'
