- alias: Hallway Light Motion Extended (Blueprint)
  id: hallway_light_motion_extended
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
        - binary_sensor.hallway_motion_sensor_occupancy
      light_switch:
        entity_id: light.hallway_light
      time_delay: 0.5
      include_ambient: ambient_enabled
      ambient_light_sensor: sensor.hallway_motion_sensor_illuminance
      ambient_light_options: ambient_light_option_enabled

- alias: "Frigate Notifications - Thijs"
  use_blueprint:
    path: SgtBatten/Beta.yaml
    input:
      camera:
        - camera.driveway
        - camera.backyard
      notify_device: e4405accf87ba6b900191d60c1299b05
      base_url: https://ha.mczlik.com
      critical: "true"
      video: >-
        {{base_url}}/api/frigate{{client_id}}/notifications/{{review_id}}/review_preview.gif?format=ts
      final_update: true
      icon: >-
        mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
        else 'cat' if label == 'Cat' else 'car' if label == 'Car' else
        'home-assistant'}}
      android_auto: true
      sticky: true
      loiter_timer: 60
      telegram_base_url: http://homeassistant.internal
      notify_telegram_chat_id: "<telegram_chat_id>"
      attachment: >-
        {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg

