- platform: template
  lights:
    hallway_light:
      friendly_name: "Hallway Light"
      value_template: "{{ is_state('switch.hallway_light_switch', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.hallway_light_switch
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.hallway_light_switch
