button_card_templates:
  !include_dir_merge_named button_card_templates

views:
  - type: custom:masonry-layout
    path: home2
    title: Home
    icon: mdi:home
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            title: Living room
            cards:
              - type: custom:mini-graph-card
                name: Temperature
                entities:
                  - entity: sensor.living_room_temperature_temperature
                    name: Temperature
                show:
                  fill: true
                hours_to_show: 12
                points_per_hour: 2
              - type: custom:mini-graph-card
                name: Humidity
                entities:
                  - entity: sensor.living_room_temperature_humidity
                    name: Humidity
                show:
                  fill: true
                hours_to_show: 12
                points_per_hour: 2
                line_color: blue
          - type: horizontal-stack
            title: Bathroom
            cards:
              - type: custom:mini-graph-card
                name: Temperature
                entities:
                  - entity: sensor.bathroom_temperature_temperature
                    name: Temperature
                show:
                  fill: true
                hours_to_show: 12
                points_per_hour: 2
              - type: custom:mini-graph-card
                name: Humidity
                entities:
                  - entity: sensor.bathroom_temperature_humidity
                    name: Humidity
                show:
                  fill: true
                hours_to_show: 12
                points_per_hour: 2
                line_color: blue
          - type: horizontal-stack
            title: Bedroom
            cards:
              - type: custom:mini-graph-card
                name: Temperature
                entities:
                  - entity: sensor.bedroom_temperature_temperature
                    name: Temperature
                show:
                  fill: true
                hours_to_show: 12
                points_per_hour: 2
              - type: custom:mini-graph-card
                name: Humidity
                entities:
                  - entity: sensor.bedroom_temperature_humidity
                    name: Humidity
                show:
                  fill: true
                hours_to_show: 12
                points_per_hour: 2
                line_color: blue
          - type: horizontal-stack
            title: Office
            cards:
              - type: custom:mini-graph-card
                name: Humidity
                entities:
                  - entity: sensor.office_temperature_temperature
                    name: Humidity
                show:
                  fill: true
                hours_to_show: 12
                points_per_hour: 2
              - type: custom:mini-graph-card
                name: Temperature
                entities:
                  - entity: sensor.office_temperature_humidity
                    name: Temperature
                show:
                  fill: true
                hours_to_show: 12
                points_per_hour: 2
                line_color: blue


      - type: horizontal-stack
        cards:
          - type: custom:mushroom-person-card
            entity: person.thijs
            name: Thijs
          - type: custom:mushroom-person-card
            entity: person.sal
            name: Sal
      - type: vertical-stack
        cards:
          - type: custom:advanced-camera-card
            cameras:
              - camera_entity: camera.living
          - square: false
            type: grid
            cards:
              - type: custom:mushroom-light-card
                entity: light.living_room_dimmer
                icon: mdi:sofa
                name: Living Room
                show_brightness_control: true
                show_color_control: false
                use_light_color: false
                collapsible_controls: true
              - type: custom:mushroom-light-card
                entity: light.dining_room_dimmer
                icon: mdi:table-furniture
                name: Dining Room
                show_brightness_control: true
                collapsible_controls: true
            columns: 2
        title: Living room
      - type: vertical-stack
        cards:
          - type: custom:advanced-camera-card
            cameras:
              - camera_entity: camera.driveway
          - square: false
            type: grid
            cards:
              - type: custom:mushroom-light-card
                entity: light.hallway_light
                icon: mdi:lightbulb
                name: Hallway
                show_brightness_control: false
                show_color_control: false
                use_light_color: false
                collapsible_controls: true
              - type: custom:mushroom-entity-card
                entity: binary_sensor.hallway_motion_sensor_occupancy
                name: Occupancy
              - type: custom:mushroom-entity-card
                entity: sensor.hallway_motion_sensor_illuminance
                name: Illuminance
            columns: 2
        title: Hallway
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Temperature
                entities:
                  - entity: sensor.bathroom_temperature_temperature
                    name: Temperature
                show:
                  fill: true
                hours_to_show: 12
                points_per_hour: 2
              - type: custom:mini-graph-card
                name: Humidity
                entities:
                  - entity: sensor.bathroom_temperature_humidity
                    name: Humidity
                show:
                  fill: true
                hours_to_show: 12
                points_per_hour: 2
                line_color: blue
        title: Bathroom
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Temperature
                entities:
                  - entity: sensor.bedroom_temperature_temperature
                    name: Temperature
                show:
                  fill: true
                hours_to_show: 12
                points_per_hour: 2
              - type: custom:mini-graph-card
                name: Humidity
                entities:
                  - entity: sensor.bedroom_temperature_humidity
                    name: Humidity
                show:
                  fill: true
                hours_to_show: 12
                points_per_hour: 2
                line_color: blue
        title: Bedroom
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Humidity
                entities:
                  - entity: sensor.office_temperature_temperature
                    name: Humidity
                show:
                  fill: true
                hours_to_show: 12
                points_per_hour: 2
              - type: custom:mini-graph-card
                name: Temperature
                entities:
                  - entity: sensor.office_temperature_humidity
                    name: Temperature
                show:
                  fill: true
                hours_to_show: 12
                points_per_hour: 2
                line_color: blue
        title: Office
      - square: false
        type: grid
        cards:
          - type: custom:mushroom-entity-card
            entity: binary_sensor.backyard_person_occupancy
            name: Person occupancy
            icon: mdi:account
            icon_color: |-
              {% if is_state('binary_sensor.backyard_person_occupancy', 'on') %}
                orange
              {% else %}
                grey
              {% endif %}
          - type: custom:mushroom-entity-card
            entity: binary_sensor.backyard_dog_occupancy
            icon: mdi:dog
            name: Dog occupancy
            icon_color: |-
              {% if is_state('binary_sensor.backyard_dog_occupancy', 'on') %}
                orange
              {% else %}
                grey
              {% endif %}
          - type: custom:mushroom-entity-card
            entity: binary_sensor.backyard_cat_occupancy
            icon: mdi:cat
            name: Cat occupancy
            icon_color: |-
              {% if is_state('binary_sensor.backyard_cat_occupancy', 'on') %}
                orange
              {% else %}
                grey
              {% endif %}
        columns: 2
  - type: masonry
    path: smartmeter
    title: Smartmeter
    icon: mdi:lightning-bolt
    cards:
      - type: custom:modern-circular-gauge
        entity: sensor.currently_energy_delivered_watt
        secondary: {}
        tertiary: {}
        min: 0
        needle: true
        start_from_zero: false
        show_state: true
        show_unit: true
        adaptive_state_color: false
        header_position: top
        smooth_segments: true
        show_header: true
        show_icon: false
        adaptive_icon_color: true
        segments:
          - from: 0
            color:
              - 143
              - 255
              - 50
          - from: 800
            color:
              - 255
              - 228
              - 50
          - from: 1500
            color:
              - 196
              - 0
              - 0
        max: 2000
        name: Current Usage
        gauge_foreground_style:
          opacity: 1
          width: 8
        gauge_background_style:
          opacity: 1
          width: 4
      - type: custom:apexcharts-card
        experimental:
          color_threshold: true
        graph_span: 1h
        show:
          last_updated: true
        apex_config:
          yaxis:
            - id: first
              forceNiceScale: true
              decimalsInFloat: 3
          fill:
            type: solid
            opacity: 0.25
        header:
          standard_format: false
          show: true
          show_states: true
          colorize_states: true
          title: Past hour - median per minute
        series:
          - entity: sensor.currently_energy_delivered_watt
            name: Usage
            type: area
            group_by:
              func: median
              duration: 1m
            stroke_width: 4
          - entity: sensor.currently_energy_returned_watt
            name: Return
            type: line
            group_by:
              func: median
              duration: 1m
            stroke_width: 4
      - type: custom:apexcharts-card
        graph_span: 24h
        span:
          start: day
        header:
          show: true
          title: Usage last 24 hours
        apex_config:
          yaxis:
            - id: first
              forceNiceScale: true
              decimalsInFloat: 2
              opposite: false
              name: Energie
        series:
          - entity: sensor.energy_usage_peak_hourly
            unit: kWh
            type: column
            name: High tariff usage
            color: "#EF810E"
            group_by:
              func: max
            show:
              datalabels: false
              extremas: false
          - entity: sensor.energy_usage_offpeak_hourly
            unit: kWh
            type: column
            name: Low tariff usage
            color: "#053752"
            group_by:
              func: max
            show:
              datalabels: false
              extremas: false
      - type: energy-distribution
        link_dashboard: true
      - type: vertical-stack
        cards:
          - type: custom:mushroom-entity-card
            entity: sensor.smartmeter_mac_address
          - type: custom:mushroom-entity-card
            entity: sensor.smartmeter_ip_address
          - type: custom:mushroom-entity-card
            entity: sensor.smartmeter_startup_time
          - type: custom:mushroom-entity-card
            entity: sensor.smartmeter_wifi_signal_strength_rssi
          - type: custom:mushroom-entity-card
            entity: sensor.smartmeter_firmware_running_version
          - type: custom:mushroom-entity-card
            entity: sensor.smartmeter_firmware_available_version
          - type: custom:mushroom-entity-card
            entity: sensor.smartmeter_firmware_update_available
          - type: custom:mushroom-entity-card
            entity: switch.smartmeter_install_firmware_update
          - type: custom:mushroom-entity-card
            entity: sensor.smartmeter_lastchanged
          - type: custom:mushroom-entity-card
            entity: binary_sensor.smartmeter_connectivity_status
  - type: masonry
    path: system
    title: System
    icon: mdi:desktop-classic
    cards:
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: input_boolean.restart_required
                state: 'on'
            card:
              type: custom:button-card
              name: Restart Home Assistant
              icon: mdi:restart
              color_type: icon
              color: red
              tap_action:
                action: call-service
                confirmation:
                  text: "Restart Home Assistant now?"
                service: script.restart_homeassistant
              styles:
                card:
                  - padding: 12px
                name:
                  - font-weight: 600
                icon:
                  - width: 32px
                  - height: 32px

          - type: custom:button-card
            name: Git Pull
            icon: mdi:git
            color_type: icon
            color: var(--primary-color)
            tap_action:
              action: call-service
              service: script.git_pull
            styles:
              card:
                - padding: 12px
              name:
                - font-weight: 600
              icon:
                - width: 32px
                - height: 32px


