#shell_command:
#  git_pull: 'git -C /config pull --ff-only'
shell_command:
  git_pull: 'bash -c "cd /config && git fetch origin && git reset --hard origin/$(git rev-parse --abbrev-ref HEAD)"'
  replace_telegram_id: >
    bash -c "TELEGRAM_ID=$(grep '^telegram_chat_id:' /config/secrets.yaml | sed 's/telegram_chat_id:[[:space:]]*//' | tr -d '\"'\''') && sed -i 's/<telegram_chat_id>/'$TELEGRAM_ID'/g' /config/automations.yaml"
  get_last_commit: 'cd /config && git log -1 --pretty=format:"%s" > /tmp/last_commit.txt'

# Helper flag to indicate a restart is required
input_boolean:
  restart_required:
    name: Restart Required
    icon: mdi:restart-alert

# Sensor to read the last commit message
command_line:
  sensor:
    name: Last Git Commit
    command: 'cat /tmp/last_commit.txt 2>/dev/null || echo "No commit info"'
    scan_interval: 30 # In seconds

script:
  git_pull:
    alias: Git Pull Config
    icon: mdi:git
    sequence:
      - service: shell_command.git_pull
      - delay: "00:00:01"
      - service: script.get_commit_info
      - delay: "00:00:01"
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.restart_required
      - service: persistent_notification.create
        data:
          title: "Git Pull Completed"
          message: "Configuration updated. Restart Home Assistant to apply all changes."
          notification_id: git_pull_notice
    mode: single

  restart_homeassistant:
    alias: Restart Home Assistant
    icon: mdi:restart
    sequence:
      - service: homeassistant.restart
    mode: single

  replace_telegram_id:
    alias: Replace Telegram ID
    icon: mdi:telegram
    sequence:
      - service: shell_command.replace_telegram_id
      - service: persistent_notification.create
        data:
          title: "Telegram ID Replaced"
          message: "Successfully replaced <telegram_chat_id> placeholders with actual value from secrets.yaml"
          notification_id: telegram_id_replace_notice
    mode: single

  get_commit_info:
    alias: Get Last Commit
    icon: mdi:git
    sequence:
      - service: shell_command.get_last_commit
      - delay: "00:00:01"
      - service: homeassistant.update_entity
        target:
          entity_id: sensor.last_git_commit
    mode: single


  # Optional: run git pull and send a mobile actionable notification to restart now or later
#  git_pull_mobile_prompt:
#    alias: Git Pull + Mobile Prompt
#    icon: mdi:git
#    sequence:
#      - service: shell_command.git_pull
#      - delay: "00:00:02"
#      - service: input_boolean.turn_on
#        target:
#          entity_id: input_boolean.restart_required
#      - service: notify.mobile_app_<YOUR_DEVICE_NAME>
#        data:
#          title: "Git Pull Completed"
#          message: "Restart Home Assistant to apply changes?"
#          data:
#            actions:
#              - action: "RESTART_HA_NOW"
#                title: "Restart now"
#              - action: "DISMISS"
#                title: "Later"
#    mode: single

automation:
  # Optional: handle the mobile action to restart immediately
  - id: restart_ha_on_mobile_action
    alias: Restart HA on Mobile Action
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: RESTART_HA_NOW
    action:
      - service: homeassistant.restart

  # Optional: when Home Assistant starts, clear the flag (fresh boot implies restart was done)
  - id: clear_restart_required_on_start
    alias: Clear Restart Required on Start
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.restart_required
          
  - id: replace_telegram_id_on_start
    alias: Replace Telegram ID on Start
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: script.replace_telegram_id

