light:
  - platform: template
    lights:
      hallway_light:
        friendly_name: "Hallway Light"
        unique_id: hallway_light
        value_template: "{{ is_state('switch.hallway_light_switch', 'on') }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.hallway_light_switch
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.hallway_light_switch

  - platform: group
    name: "Office Lights"
    unique_id: office_lights_group
    entities:
      - light.office_ceiling_lamp_01
      - light.office_ceiling_lamp_02
      - light.office_ceiling_lamp_03

automation:
  - alias: Sunset lights
    id: sunset_lights
    description: Activate lights 30 min before sunset
    triggers:
      - trigger: sun
        event: sunset
        offset: "-00:30:00"
    conditions: []
    actions:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 25
        target:
          entity_id: light.dining_room_dimmer
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 75
        target:
          entity_id: light.living_room_dimmer
    mode: single

  - alias: Office lights dynamic brightness
    id: office_lights_dynamic_brightness
    description: Adjust office lights brightness based on sun position and time
    mode: restart
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.office_presence_occupancy
      - trigger: time_pattern
        minutes: "/15"  # Check every 15 minutes
      - trigger: sun
        event: sunrise
      - trigger: sun
        event: sunset
    conditions:
      - condition: state
        entity_id: binary_sensor.office_presence_occupancy
        state: "on"
    actions:
      - action: light.turn_on
        target:
          entity_id: light.office_lights
        data:
          brightness_pct: >
            {% set now_hour = now().hour %}
            {% set sun_elevation = state_attr('sun.sun', 'elevation') %}
            
            {# Work hours: 8 AM to 5 PM - full brightness #}
            {% if now_hour >= 8 and now_hour < 17 %}
              100
            {# Evening hours: 5 PM to 10 PM - dim based on sun elevation #}
            {% elif now_hour >= 17 and now_hour < 22 %}
              {% if sun_elevation > 10 %}
                80
              {% elif sun_elevation > 0 %}
                60
              {% elif sun_elevation > -10 %}
                40
              {% else %}
                25
              {% endif %}
            {# Night hours: 10 PM to 8 AM - very dim #}
            {% else %}
              15
            {% endif %}

  - alias: Office lights presence
    id: office_lights_presence
    description: Turn off office lights when no presence
    mode: single
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.office_presence_occupancy
        to: "off"
    conditions: []
    actions:
      - action: light.turn_off
        target:
          entity_id: light.office_lights


